/* Owned by Troobaflowsite — edit this file directly. */
export const meta = {
  "title": "Terms | Trooba Flow",
  "description": "The terms under which this website and the Trooba Flow service are provided, and how measured and modelled figures on this site should be read.",
  "canonical": "https://www.trooba.com/terms.html",
  "ogTitle": "Terms | Trooba Flow",
  "ogDescription": "The terms under which this website and the Trooba Flow service are provided, and how measured and modelled figures on this site should be read.",
  "ogUrl": "https://www.trooba.com/terms.html"
} as const;

export const mainHtml = "<section class=\"phead\"><div class=\"wrap\"><div class=\"measure\"><h1 class=\"section-title section-title--wide\">Terms</h1><p class=\"lead\">The terms under which this website and the Trooba Flow service are provided, and how measured and modelled figures on this site should be read.</p><p class=\"meta u-mt6\">Last updated August 2026</p></div></div></section><section class=\"section--tight\"><div class=\"wrap\"><div class=\"measure\"><h2 class=\"h3 u-mt10\">This website</h2><p class=\"body u-mt4\">The trooba.com website is provided as is, for information. We keep it accurate and correct errors when we find them, but we do not warrant that every page is complete or current.</p><h2 class=\"h3 u-mt10\">Figures shown on this site</h2><p class=\"body u-mt4\">Diagrams and product views on this site are built from an <strong>illustrative model</strong> unless a page states otherwise, and are labelled where they appear. They demonstrate how the software behaves; they are not a forecast of your results.</p><p class=\"body u-mt4\">Where a page presents a <strong>measured</strong> result, it was observed in a factory after a change was made. Where it presents a <strong>modelled</strong> result, it is what the model projects. We label which is which, and neither is a performance guarantee.</p><h2 class=\"h3 u-mt10\">The Trooba Flow service</h2><p class=\"body u-mt4\">Use of the application is governed by the written agreement signed with your organisation. Where that agreement and this page differ, the agreement takes precedence.</p><h2 class=\"h3 u-mt10\">Modelled results and your judgement</h2><p class=\"body u-mt4\">Trooba Flow produces modelled projections about manufacturing flow. They are a decision aid. Operating, safety, capital and staffing decisions remain yours, and should be taken with your own engineering judgement applied to them.</p><h2 class=\"h3 u-mt10\">Intellectual property</h2><p class=\"body u-mt4\">The Trooba name, the Flow Helix mark, the Trooba Flow product identity, the software and the content of this site belong to Trooba. Your factory data, your models and your results remain yours.</p><h2 class=\"h3 u-mt10\">Liability</h2><p class=\"body u-mt4\">Nothing here excludes liability that cannot lawfully be excluded. Subject to that, and to any signed agreement, our liability arising from this website is limited to the extent permitted by law.</p><h2 class=\"h3 u-mt10\">Contact</h2><p class=\"body u-mt4\">Trooba can be reached at hello@trooba.com.</p><p class=\"body u-mt10\" style=\"padding-top:var(--space-6);border-top:1px solid var(--border-subtle)\">Questions about this page go to <a href=\"mailto:hello@trooba.com\">hello@trooba.com</a>.</p></div></div></section>";
